answer_question_task:
  description: |
    Beantworte die folgende Frage über die 7 Lebenszyklen basierend auf dem bereitgestellten Kontext.
    
    Frage: {question}
    
    Kontext aus der Wissensdatenbank:
    {context}
    
    Anweisungen:
    - Gib eine klare, umfassende Antwort basierend auf dem Kontext
    - Wenn die Frage anhand des Kontexts nicht beantwortet werden kann, sage das deutlich
    - Beziehe dich spezifisch auf das 7-Zyklen-Konzept, wenn relevant
    - Halte die Antwort fokussiert und praktisch
    - Formatiere die Antwort klar und gut lesbar
    - WICHTIG: Antworte IMMER auf Deutsch, auch wenn die Frage auf Englisch gestellt wurde
  expected_output: "Eine klare, gut strukturierte Antwort auf die Frage basierend auf der 7 Lebenszyklen Wissensdatenbank"
  agent: qa_agent

knowledge_overview_task:
  description: |
    Erstelle eine umfassende Übersicht über die 7 Lebenszyklen Wissensdatenbank.
    
    Beispielinhalt:
    {sample_content}
    
    Anweisungen:
    - Fasse die Hauptkonzepte und Prinzipien zusammen
    - Liste die verschiedenen behandelten Zyklen auf
    - Erkläre, wie dieses Wissen angewendet werden kann
    - Halte es prägnant aber informativ
    - WICHTIG: Erstelle die Übersicht auf Deutsch
  expected_output: "Eine umfassende Übersicht über die 7 Lebenszyklen Wissensdatenbank"
  agent: qa_agent

generate_affirmations_task:
  description: |
    Erstelle {count} kraftvolle Affirmationen für die 7 Cycles Periode "{period_name}".
    
    7 Cycles Periode: {period_name}
    Farbe: {period_color}
    Zusätzliche Informationen: {period_info}
    
    Kontext aus der Wissensdatenbank:
    {context}
    
    SPEZIFISCHE ANWEISUNGEN FÜR JEDE PERIODE:
    
    IMAGE (#DAA520 - Goldgrün):
    - Fokus: Selbstbild, Identität, Selbstwahrnehmung, persönliche Ausstrahlung
    - Themen: Selbstvertrauen, Authentizität, Selbstliebe, positive Selbstwahrnehmung
    - Schlüsselwörter: "Ich bin", "Mein wahres Selbst", "Meine Ausstrahlung", "Meine Identität"
    
    VERÄNDERUNG (#2196F3 - Blau):
    - Fokus: Transformation, Wandel, Anpassung, Neubeginn
    - Themen: Mut zur Veränderung, Flexibilität, Wachstum, Transformation
    - Schlüsselwörter: "Ich verändere", "Ich wachse", "Neue Wege", "Transformation"
    
    ENERGIE (#F44336 - Rot):
    - Fokus: Vitalität, Schwung, Dynamik, körperliche/mentale Kraft
    - Themen: Lebenskraft, Motivation, Ausdauer, vitale Energie
    - Schlüsselwörter: "Meine Energie", "Ich bin kraftvoll", "Vitalität", "Schwung"
    
    KREATIVITÄT (#FFD700 - Gold):
    - Fokus: Innovation, Inspiration, Schöpfung, künstlerischer Ausdruck
    - Themen: Kreative Entfaltung, Inspiration, Innovation, künstlerische Kraft
    - Schlüsselwörter: "Ich erschaffe", "Meine Kreativität", "Innovation", "Inspiration"
    
    ERFOLG (#CC0066 - Magenta):
    - Fokus: Zielerreichung, Leistung, Manifestation, Erfolgserlebnisse
    - Themen: Ziele erreichen, Erfolg manifestieren, Leistung, Anerkennung
    - Schlüsselwörter: "Ich erreiche", "Mein Erfolg", "Ziele verwirklichen", "Erfolgreiche Umsetzung"
    
    ENTSPANNUNG (#4CAF50 - Grün):
    - Fokus: Ruhe, Regeneration, Balance, innerer Frieden
    - Themen: Gelassenheit, Erholung, Balance, innere Ruhe
    - Schlüsselwörter: "Ich entspanne", "Innere Ruhe", "Balance", "Gelassenheit"
    
    UMSICHT (#9C27B0 - Lila):
    - Fokus: Weisheit, Besonnenheit, durchdachte Planung, weise Entscheidungen
    - Themen: Weisheit, Besonnenheit, kluge Entscheidungen, strategisches Denken
    - Schlüsselwörter: "Ich entscheide weise", "Meine Weisheit", "Besonnenheit", "Klare Sicht"
    
    ALLGEMEINE ANWEISUNGEN:
    - Jede Affirmation sollte 8-15 Wörter lang sein
    - Verwende die Ich-Form und Gegenwartsform
    - Integriere die spezifischen Schlüsselwörter der jeweiligen Periode
    - Mache sie emotional kraftvoll und motivierend
    - Stelle sicher, dass sie zur Energie der Periode passen
    - WICHTIG: Alle Affirmationen müssen auf Deutsch sein!
    
    Formatiere als JSON:
    {{
        "affirmations": [
            {{
                "text": "Affirmationstext",
                "theme": "{period_name}",
                "focus": "Spezifischer Fokus dieser Affirmation innerhalb der Periode",
                "period_color": "{period_color}"
            }}
        ]
    }}
  expected_output: "JSON formatierte Liste von Affirmationen spezifisch für die gewählte 7 Cycles Periode"
  agent: affirmations_agent

search_images_task:
  description: |
    Suche nach passenden Hintergrundbildern für visuelle Affirmationen basierend auf den gegebenen Tags und der 7 Cycles Periode.
    
    Eingabe-Parameter:
    - tags: {tags} (Liste von Suchbegriffen)
    - period: {period} (7 Cycles Periode)
    - count: {count} (Anzahl der zu suchenden Bilder)
    
    Suche nach Bildern, die:
    1. Zur Periode {period} passen und deren Energie widerspiegeln
    2. Hochwertig und ästhetisch ansprechend sind
    3. Als Hintergrund für Text geeignet sind
    4. Die passende Stimmung und Farben haben
    
    Nutze die Pexels API für die Suche und berücksichtige:
    - Bildqualität (mindestens 1080px Breite)
    - Portrait-Orientierung (für Instagram Stories)
    - Lizenzkonformität
    - Emotionale Wirkung
  expected_output: "Liste von passenden Hintergrundbildern mit URLs, Metadaten und Lizenzinformationen"
  agent: image_search_agent

create_visual_post_task:
  description: |
    Erstelle einen visuellen Affirmations-Post im Instagram Story Format (1080x1920px) mit:
    
    Eingabe-Parameter:
    - text: {text} (Affirmationstext)
    - period: {period} (7 Cycles Periode)
    - tags: {tags} (Tags für Hintergrundbildsuche)
    - image_style: {image_style} (Stil: minimal, dramatic, gradient)
    - background_image: {background_image} (Optional: spezifisches Hintergrundbild)
    
    Erstelle einen Post mit:
    1. Passendem Hintergrundbild (über Bildsuche oder bereitgestellt)
    2. Farb-Overlay basierend auf der 7 Cycles Periode:
       - Image: #DAA520 (Gold)
       - Veränderung: #2196F3 (Blau)
       - Energie: #F44336 (Rot)
       - Kreativität: #FFD700 (Gelb)
       - Erfolg: #CC0066 (Magenta)
       - Entspannung: #4CAF50 (Grün)
       - Umsicht: #9C27B0 (Lila)
    3. Zentriertem, gut lesbarem Text mit Schatten
    4. Modernem, ansprechendem Design
    
    Speichere das finale Bild als JPG mit 95% Qualität.
  expected_output: "Pfad zum erstellten visuellen Post mit Metadaten (Größe, Format, Farben)"
  agent: visual_post_creator_agent

generate_instagram_post_task:
  description: |
    Erstelle einen ansprechenden Instagram Post für die 7 Cycles Periode "{period_name}" mit der folgenden Affirmation:
    
    Affirmation: "{affirmation}"
    
    Perioden-Information:
    - Name: {period_name}
    - Farbe: {period_color}
    - Fokus: {period_focus}
    - Beschreibung: {period_description}
    - Schlüsselwörter: {period_keywords}
    
    Kontext aus der 7 Cycles Wissensdatenbank:
    {context}
    
    Stil: {style}
    
    Erstelle einen vollständigen Instagram Post mit:
    
    1. POST TEXT (150-200 Wörter):
       - Beginne mit einem ansprechenden Hook zur Periode
       - Integriere die Affirmation natürlich in den Text
       - Biete Kontext über die {period_name} Periode aus dem 7 Cycles System
       - Mache es nachvollziehbar und inspirierend
       - Beende mit einem überzeugenden Call-to-Action
    
    2. HASHTAGS (25-30 Hashtags):
       - Mix aus trending Personal Development Hashtags
       - 7 Cycles spezifische Hashtags
       - Perioden-spezifische Hashtags für {period_name}
       - Community Building Hashtags
       - Engagement-fokussierte Hashtags
       
    3. CALL-TO-ACTION:
       - Ermutige zu sinnvollem Engagement (Kommentare, Shares, Saves)
       - Stelle zum Nachdenken anregende Fragen
       - Lade Follower ein, ihre Erfahrungen zu teilen
       - Fördere Community-Interaktion
    
    4. ENGAGEMENT-STRATEGIEN:
       - Empfehle optimale Posting-Zeiten
       - Schlage Story Follow-up Content vor
       - Gib Tipps für Community Building
    
    Formatiere die Antwort als JSON:
    {{
        "post_text": "Vollständiger Instagram Post Text mit natürlicher Affirmations-Integration",
        "hashtags": ["#hashtag1", "#hashtag2", ...],
        "call_to_action": "Spezifischer Call-to-Action Text",
        "engagement_strategies": ["strategie1", "strategie2", ...],
        "optimal_posting_time": "Empfohlene Posting-Zeit",
        "period_name": "{period_name}",
        "period_color": "{period_color}",
        "affirmation": "{affirmation}",
        "style": "{style}"
    }}
  expected_output: "JSON formatierter Instagram Post mit Text, Hashtags, Call-to-Action und Engagement-Strategien"
  agent: write_hashtag_research_agent

android_app_test_task:
  description: |
    Führe einen automatisierten Test für die Android-App durch:
    
    APK-Datei: {apk_path}
    Ziel-API-Level: {target_api_level}
    Test-Aktionen: {test_actions}
    AVD-Name: {avd_name}
    
    Führe folgende Tests durch:
    
    1. APP-START UND STABILITÄT:
       - Installiere die App im Emulator
       - Überprüfe erfolgreichen Start
       - Messe Startzeit in Millisekunden
       - Dokumentiere Startup-Exceptions
    
    2. NAVIGATIONS-TEST:
       - Klicke systematisch durch alle erreichbaren Screens
       - Teste Zurück-Navigation
       - Überprüfe Screen-Übergänge
       - Dokumentiere nicht erreichbare Bereiche
    
    3. FEHLER-ERKENNUNG:
       - Überwache Logcat auf Crashes und Exceptions
       - Erkenne ANRs (Application Not Responding)
       - Identifiziere leere Views oder fehlende Inhalte
       - Dokumentiere lange Ladezeiten (>3 Sekunden)
    
    4. PERFORMANCE-METRIKEN:
       - CPU-Auslastung (Durchschnitt und Spitzen)
       - Memory-Verbrauch (Heap und Native)
       - Frame-Rate und UI-Jank
       - Battery-Drain-Schätzung
       - Netzwerk-Traffic (falls relevant)
    
    5. UX-OPTIMIERUNGSPOTENTIALE:
       - Unklare oder zu kleine Buttons (<48dp)
       - Zu lange User-Flows (>3 Klicks für Hauptfunktionen)
       - Inkonsistente UI-Elemente
       - Fehlende oder verwirrende Labels
    
    6. BARRIEREFREIHEIT:
       - Content-Descriptions für Screen-Reader
       - Touch-Target-Größen
       - Farb-Kontraste
       - Keyboard-Navigation (falls unterstützt)
    
    Erstelle einen strukturierten Bericht mit:
    - Zusammenfassung (bestanden/fehlgeschlagen)
    - Kritische Fehler mit Priorität
    - Performance-Bewertung mit Metriken
    - UX-Empfehlungen sortiert nach Impact
    - Accessibility-Score und Verbesserungen
    - Screenshots von Problemen
  expected_output: "Strukturierter Testbericht mit Fehlern, Performance-Analyse, UX-Empfehlungen und Accessibility-Bewertung"
  agent: android_testing_agent

android_performance_analysis_task:
  description: |
    Analysiere die Performance-Daten der Android-App im Detail:
    
    Package-Name: {package_name}
    Test-ID: {test_id}
    
    Führe eine tiefgreifende Analyse durch:
    
    1. PERFORMANCE-PROFILING:
       - Detaillierte CPU-Nutzung pro Thread
       - Memory-Leaks und Garbage Collection
       - GPU-Rendering-Performance
       - Disk I/O und Database-Operationen
    
    2. STARTUP-OPTIMIERUNG:
       - Cold-Start vs. Warm-Start Zeiten
       - Main-Thread-Blockierungen
       - Lazy-Loading-Möglichkeiten
       - Splash-Screen-Optimierung
    
    3. UI-PERFORMANCE:
       - Frame-Drops und Jank-Ursachen
       - Overdraw-Analyse
       - Layout-Performance
       - Animation-Smoothness
    
    4. BATTERY-OPTIMIERUNG:
       - Wake-Lock-Nutzung
       - Background-Services
       - Location-Updates
       - Network-Requests
    
    Erstelle konkrete Optimierungsvorschläge mit:
    - Priorisierung nach Impact
    - Geschätzter Aufwand
    - Erwartete Verbesserung
    - Code-Beispiele wo möglich
  expected_output: "Detaillierte Performance-Analyse mit konkreten Optimierungsvorschlägen"
  agent: android_testing_agent

android_accessibility_audit_task:
  description: |
    Führe ein umfassendes Accessibility-Audit der Android-App durch:
    
    Package-Name: {package_name}
    UI-Dump: {ui_dump}
    Screenshots: {screenshots}
    
    Prüfe folgende Accessibility-Aspekte:
    
    1. SCREEN-READER-UNTERSTÜTZUNG:
       - Content-Descriptions für alle interaktiven Elemente
       - Sinnvolle Label für Buttons und Controls
       - Gruppierung zusammengehöriger Elemente
       - Fokus-Reihenfolge
    
    2. VISUELLE BARRIEREFREIHEIT:
       - Farb-Kontraste (WCAG AA/AAA Standards)
       - Text-Größen (min. 12sp)
       - Touch-Target-Größen (min. 48x48dp)
       - Keine Farbe als einziger Informationsträger
    
    3. MOTOR-BARRIEREFREIHEIT:
       - Ausreichend große Touch-Targets
       - Keine präzisen Gesten erforderlich
       - Alternative Eingabemethoden
       - Timeout-Anpassungen
    
    4. KOGNITIVE BARRIEREFREIHEIT:
       - Klare, konsistente Navigation
       - Verständliche Fehlermeldungen
       - Einfache Sprache
       - Hilfe-Funktionen
    
    Erstelle einen Bericht mit:
    - Accessibility-Score (0-100)
    - Kritische Barrieren
    - WCAG-Konformität
    - Konkrete Verbesserungsvorschläge
    - Best-Practice-Beispiele
  expected_output: "Umfassender Accessibility-Bericht mit Score, Barrieren und Verbesserungsvorschlägen"
  agent: android_testing_agent

threads_profile_analysis:
  description: |
    Analyze the following Threads profiles to extract content patterns and strategies:
    
    Profiles to analyze: {handles}
    
    Instructions:
    - Analyze posting frequency and timing patterns
    - Identify content themes and formats
    - Extract hashtag strategies
    - Understand engagement tactics
    - Recognize visual and textual patterns
    - Note community building approaches
    
    Use the analyze_threads_profile tool for each handle and synthesize insights.
    
    Provide actionable recommendations for 7 Cycles content strategy.
  expected_output: "Comprehensive analysis of Threads profiles with patterns, strategies, and recommendations"
  agent: threads_analyst

threads_strategy_creation:
  description: |
    Create a comprehensive Threads content strategy based on:
    
    Competitive Analysis: {analysis}
    Brand Values: 7 Cycles methodology - rhythm, spirituality, energy, empowerment
    Available Resources: Affirmations, activities catalog, knowledge base
    
    Instructions:
    - Define content pillars aligned with 7 Cycles periods
    - Create posting schedule (frequency, timing, days)
    - Develop hashtag strategy for discovery
    - Design engagement tactics
    - Set growth milestones and KPIs
    
    The strategy should:
    - Build authentic community
    - Share transformative wisdom
    - Inspire daily practice
    - Foster meaningful engagement
  expected_output: "Complete Threads content strategy with pillars, schedule, tactics, and KPIs"
  agent: threads_strategy

threads_post_generation:
  description: |
    Generate {count} Threads posts based on:
    
    Strategy: {strategy}
    Current Period: {period}
    Theme: {theme}
    Include Affirmations: {include_affirmations}
    Include Activities: {include_activities}
    
    Available Resources:
    - Affirmations: {affirmations}
    - Activities: {activities}
    - Knowledge Context: {knowledge_context}
    
    Each post must:
    - Start with attention-grabbing hook
    - Deliver value in 280-500 characters
    - Include relevant call-to-action
    - Use 5-10 strategic hashtags
    - Align with period energy
    - Encourage engagement
    
    Vary formats: quotes, mini-lessons, activities, questions, stories
    
    IMPORTANT: Create posts in German unless specified otherwise!
  expected_output: "JSON array of Threads posts with content, hashtags, period, and visual prompts"
  agent: threads_generator

threads_approval_request:
  description: |
    Review and prepare the following Threads posts for approval:
    
    Posts to review: {posts}
    
    For each post, evaluate:
    - 7 Cycles philosophy alignment
    - Message clarity and impact
    - Engagement potential
    - Community guidelines compliance
    - Visual element requirements
    - Hashtag relevance
    
    Prepare approval request with:
    - Post summary
    - Quality assessment
    - Recommended changes (if any)
    - Approval status recommendation
    
    Format for easy review and decision making.
  expected_output: "Structured approval request with assessments and recommendations"
  agent: threads_approval

threads_scheduling:
  description: |
    Schedule the following approved Threads posts:
    
    Approved Posts: {posts}
    Scheduling Window: {start_date} to {end_date}
    
    Consider:
    - Optimal posting times for target audience
    - Content type and urgency
    - Period-specific timing
    - Platform algorithm preferences
    - Consistent posting rhythm
    
    Apply timing strategy:
    - Morning (7-9 AM): Inspiration and affirmations
    - Midday (12-1 PM): Quick tips and activities
    - Evening (6-8 PM): Reflection and community
    - Weekends: Deeper wisdom and practices
    
    Create schedule ensuring:
    - Even distribution
    - Peak engagement times
    - Variety in content types
    - No overwhelming frequency
  expected_output: "Detailed posting schedule with dates, times, and content distribution"
  agent: threads_scheduler