# Tools configuration for CrewAI agents
# Currently, the PDF knowledge base is loaded programmatically in the agent classes

pdf_loader:
  type: "PyPDFLoader"
  path: "knowledge/20250607_7Cycles of Life_Ebook.pdf"

text_splitter:
  type: "RecursiveCharacterTextSplitter"
  chunk_size: 1000
  chunk_overlap: 200

vector_store:
  type: "FAISS"
  embeddings_provider: "openai"

affirmations_storage:
  type: "json"
  path: "static/affirmations_storage.json"

llm_config:
  model: "gpt-4o-mini"
  temperature: 0.7
  max_tokens: 2000