answer_question_task:
  description: |
    Beantworte die folgende Frage über die 7 Lebenszyklen basierend auf dem bereitgestellten Kontext.
    
    Frage: {question}
    
    Kontext aus der Wissensdatenbank:
    {context}
    
    Anweisungen:
    - Gib eine klare, umfassende Antwort basierend auf dem Kontext
    - Wenn die Frage anhand des Kontexts nicht beantwortet werden kann, sage das deutlich
    - Beziehe dich spezifisch auf das 7-Zyklen-Konzept, wenn relevant
    - Halte die Antwort fokussiert und praktisch
    - Formatiere die Antwort klar und gut lesbar
    - WICHTIG: Antworte IMMER auf Deutsch, auch wenn die Frage auf Englisch gestellt wurde
  expected_output: "Eine klare, gut strukturierte Antwort auf die Frage basierend auf der 7 Lebenszyklen Wissensdatenbank"
  agent: qa_agent

knowledge_overview_task:
  description: |
    Erstelle eine umfassende Übersicht über die 7 Lebenszyklen Wissensdatenbank.
    
    Beispielinhalt:
    {sample_content}
    
    Anweisungen:
    - Fasse die Hauptkonzepte und Prinzipien zusammen
    - Liste die verschiedenen behandelten Zyklen auf
    - Erkläre, wie dieses Wissen angewendet werden kann
    - Halte es prägnant aber informativ
    - WICHTIG: Erstelle die Übersicht auf Deutsch
  expected_output: "Eine umfassende Übersicht über die 7 Lebenszyklen Wissensdatenbank"
  agent: qa_agent

generate_affirmations_task:
  description: |
    Erstelle {count} kraftvolle Affirmationen für die 7 Cycles Periode "{period_name}".
    
    7 Cycles Periode: {period_name}
    Farbe: {period_color}
    Zusätzliche Informationen: {period_info}
    
    Kontext aus der Wissensdatenbank:
    {context}
    
    SPEZIFISCHE ANWEISUNGEN FÜR JEDE PERIODE:
    
    IMAGE (#DAA520 - Goldgrün):
    - Fokus: Selbstbild, Identität, Selbstwahrnehmung, persönliche Ausstrahlung
    - Themen: Selbstvertrauen, Authentizität, Selbstliebe, positive Selbstwahrnehmung
    - Schlüsselwörter: "Ich bin", "Mein wahres Selbst", "Meine Ausstrahlung", "Meine Identität"
    
    VERÄNDERUNG (#2196F3 - Blau):
    - Fokus: Transformation, Wandel, Anpassung, Neubeginn
    - Themen: Mut zur Veränderung, Flexibilität, Wachstum, Transformation
    - Schlüsselwörter: "Ich verändere", "Ich wachse", "Neue Wege", "Transformation"
    
    ENERGIE (#F44336 - Rot):
    - Fokus: Vitalität, Schwung, Dynamik, körperliche/mentale Kraft
    - Themen: Lebenskraft, Motivation, Ausdauer, vitale Energie
    - Schlüsselwörter: "Meine Energie", "Ich bin kraftvoll", "Vitalität", "Schwung"
    
    KREATIVITÄT (#FFD700 - Gold):
    - Fokus: Innovation, Inspiration, Schöpfung, künstlerischer Ausdruck
    - Themen: Kreative Entfaltung, Inspiration, Innovation, künstlerische Kraft
    - Schlüsselwörter: "Ich erschaffe", "Meine Kreativität", "Innovation", "Inspiration"
    
    ERFOLG (#CC0066 - Magenta):
    - Fokus: Zielerreichung, Leistung, Manifestation, Erfolgserlebnisse
    - Themen: Ziele erreichen, Erfolg manifestieren, Leistung, Anerkennung
    - Schlüsselwörter: "Ich erreiche", "Mein Erfolg", "Ziele verwirklichen", "Erfolgreiche Umsetzung"
    
    ENTSPANNUNG (#4CAF50 - Grün):
    - Fokus: Ruhe, Regeneration, Balance, innerer Frieden
    - Themen: Gelassenheit, Erholung, Balance, innere Ruhe
    - Schlüsselwörter: "Ich entspanne", "Innere Ruhe", "Balance", "Gelassenheit"
    
    UMSICHT (#9C27B0 - Lila):
    - Fokus: Weisheit, Besonnenheit, durchdachte Planung, weise Entscheidungen
    - Themen: Weisheit, Besonnenheit, kluge Entscheidungen, strategisches Denken
    - Schlüsselwörter: "Ich entscheide weise", "Meine Weisheit", "Besonnenheit", "Klare Sicht"
    
    ALLGEMEINE ANWEISUNGEN:
    - Jede Affirmation sollte 8-15 Wörter lang sein
    - Verwende die Ich-Form und Gegenwartsform
    - Integriere die spezifischen Schlüsselwörter der jeweiligen Periode
    - Mache sie emotional kraftvoll und motivierend
    - Stelle sicher, dass sie zur Energie der Periode passen
    - WICHTIG: Alle Affirmationen müssen auf Deutsch sein!
    
    Formatiere als JSON:
    {{
        "affirmations": [
            {{
                "text": "Affirmationstext",
                "theme": "{period_name}",
                "focus": "Spezifischer Fokus dieser Affirmation innerhalb der Periode",
                "period_color": "{period_color}"
            }}
        ]
    }}
  expected_output: "JSON formatierte Liste von Affirmationen spezifisch für die gewählte 7 Cycles Periode"
  agent: affirmations_agent

search_images_task:
  description: |
    Suche nach passenden Hintergrundbildern für visuelle Affirmationen basierend auf den gegebenen Tags und der 7 Cycles Periode.
    
    Eingabe-Parameter:
    - tags: {tags} (Liste von Suchbegriffen)
    - period: {period} (7 Cycles Periode)
    - count: {count} (Anzahl der zu suchenden Bilder)
    
    Suche nach Bildern, die:
    1. Zur Periode {period} passen und deren Energie widerspiegeln
    2. Hochwertig und ästhetisch ansprechend sind
    3. Als Hintergrund für Text geeignet sind
    4. Die passende Stimmung und Farben haben
    
    Nutze die Pexels API für die Suche und berücksichtige:
    - Bildqualität (mindestens 1080px Breite)
    - Portrait-Orientierung (für Instagram Stories)
    - Lizenzkonformität
    - Emotionale Wirkung
  expected_output: "Liste von passenden Hintergrundbildern mit URLs, Metadaten und Lizenzinformationen"
  agent: image_search_agent

create_visual_post_task:
  description: |
    Erstelle einen visuellen Affirmations-Post im Instagram Story Format (1080x1920px) mit:
    
    Eingabe-Parameter:
    - text: {text} (Affirmationstext)
    - period: {period} (7 Cycles Periode)
    - tags: {tags} (Tags für Hintergrundbildsuche)
    - image_style: {image_style} (Stil: minimal, dramatic, gradient)
    - background_image: {background_image} (Optional: spezifisches Hintergrundbild)
    
    Erstelle einen Post mit:
    1. Passendem Hintergrundbild (über Bildsuche oder bereitgestellt)
    2. Farb-Overlay basierend auf der 7 Cycles Periode:
       - Image: #DAA520 (Gold)
       - Veränderung: #2196F3 (Blau)
       - Energie: #F44336 (Rot)
       - Kreativität: #FFD700 (Gelb)
       - Erfolg: #CC0066 (Magenta)
       - Entspannung: #4CAF50 (Grün)
       - Umsicht: #9C27B0 (Lila)
    3. Zentriertem, gut lesbarem Text mit Schatten
    4. Modernem, ansprechendem Design
    
    Speichere das finale Bild als JPG mit 95% Qualität.
  expected_output: "Pfad zum erstellten visuellen Post mit Metadaten (Größe, Format, Farben)"
  agent: visual_post_creator_agent