answer_question_task:
  description: |
    Beantworte die folgende Frage über die 7 Lebenszyklen basierend auf dem bereitgestellten Kontext.
    
    Frage: {question}
    
    Kontext aus der Wissensdatenbank:
    {context}
    
    Anweisungen:
    - Gib eine klare, umfassende Antwort basierend auf dem Kontext
    - Wenn die Frage anhand des Kontexts nicht beantwortet werden kann, sage das deutlich
    - Beziehe dich spezifisch auf das 7-Zyklen-Konzept, wenn relevant
    - Halte die Antwort fokussiert und praktisch
    - Formatiere die Antwort klar und gut lesbar
    - WICHTIG: Antworte IMMER auf Deutsch, auch wenn die Frage auf Englisch gestellt wurde
  expected_output: "Eine klare, gut strukturierte Antwort auf die Frage basierend auf der 7 Lebenszyklen Wissensdatenbank"
  agent: qa_agent

knowledge_overview_task:
  description: |
    Erstelle eine umfassende Übersicht über die 7 Lebenszyklen Wissensdatenbank.
    
    Beispielinhalt:
    {sample_content}
    
    Anweisungen:
    - Fasse die Hauptkonzepte und Prinzipien zusammen
    - Liste die verschiedenen behandelten Zyklen auf
    - Erkläre, wie dieses Wissen angewendet werden kann
    - Halte es prägnant aber informativ
    - WICHTIG: Erstelle die Übersicht auf Deutsch
  expected_output: "Eine umfassende Übersicht über die 7 Lebenszyklen Wissensdatenbank"
  agent: qa_agent

generate_affirmations_task:
  description: |
    Erstelle {count} kraftvolle Affirmationen für die {period_type}-Periode basierend auf dem 7 Lebenszyklen-Wissen.
    
    Perioden-Typ: {period_type}
    Perioden-Information: {period_info}
    
    Kontext aus der Wissensdatenbank:
    {context}
    
    Anweisungen:
    - Erstelle Affirmationen, die mit den natürlichen Rhythmen dieser spezifischen Periode übereinstimmen
    - Jede Affirmation sollte positiv, in der Gegenwartsform und persönlich stärkend sein
    - Fokussiere auf die einzigartigen Eigenschaften und Möglichkeiten dieser Periode
    - Integriere Themen wie Energie, Kreativität, Erfolg und Einklang mit natürlichen Zyklen
    - Mache sie praktisch und im Alltag anwendbar
    - Jede Affirmation sollte 10-20 Wörter lang sein
    - Stelle Vielfalt in den Fokusbereich sicher (Energie, Kreativität, Erfolg, Beziehungen, Wachstum)
    - WICHTIG: Alle Affirmationen müssen auf Deutsch sein!
    
    Formatiere als JSON:
    {{
        "affirmations": [
            {{
                "text": "Affirmationstext",
                "theme": "energie/kreativitaet/erfolg/beziehungen/wachstum",
                "focus": "Kurze Beschreibung des Fokus dieser Affirmation"
            }}
        ]
    }}
  expected_output: "JSON formatierte Liste von Affirmationen mit Themen und Fokusbereichen"
  agent: affirmations_agent